### PR TITLE
Add applicable clinical trial

### PR DESCRIPTION
**Pull request by dstuck**
Adding strict computation of applicable clinical trial.

### CODE REVIEW

**Comment by dstuck** [comment]
Couldn't get this formatted well so copying in an image of table breaking down how all trials shake out in terms of eligibility
image

**Comment by dstuck** [comment]
@tomquisel I think the 65765 trials with is_major_drug_test as None are the most likely to contain actual applicable trials we could be missing and the 100708 trials with is_under_fda_oversight and is_major_drug_test None are the others we have are likely missing applicable trials from

**Comment by dstuck** [comment]
@tomquisel We lose a lot of applicable data by implementing this strictly, but probably best to start from here and work to find ways to include more trials. This is ready to review and has been tested alongside https://github.com/dstuck/clinical-trials-status-store/pull/8

**Review by tomquisel — APPROVED** [review]
Nice! I agree, this is a great starting point. We can expand out from here. I'm really excited about your progress too! I'll be back at it soon 😄.

Let me know when it's merged and I'll update the production backend.

**Comment by dstuck** [comment]
@tomquisel Great! Just merged them both

**Pull request merged**
